image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/ro-ro-statuspage-dev-repo
  tag: "fea91d6-dirty-20260906233547"
  pullPolicy: IfNotPresent

config:
  DB_HOST: ro-ro-statuspage-db.cx248m4we6k7.us-east-1.rds.amazonaws.com
  DB_PORT: "5432"
  DB_NAME: statuspage
  DB_USER: statuspage
  REDIS_HOST: master.ro-ro-statuspage-redis.7fftml.use1.cache.amazonaws.com
  SITE_URL: "http://roro-status.duckdns.org"

secrets:
  region: us-east-1
  rdsSecretName: "rds!db-6dcfeb3d-1ba7-4ee6-ab4b-4a2eaef5b280"
  appSecretName: "statuspage/app"

processes:
  web:
    command: ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8001 statuspage.wsgi"]
    service: true
    port: 8001
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
  worker:
    command: ["python", "manage.py", "rqworker", "high", "default", "low"]
    replicas: 1
    service: false
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"
  scheduler:
    command: ["python", "manage.py", "rqscheduler"]
    replicas: 1
    service: false
    strategy: Recreate
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

migrationJob:
  enabled: true
  command:
    - "sh"
    - "-c"
    - "python manage.py migrate && (python manage.py collectstatic --no-input || true) && (python manage.py createsuperuser --noinput || true)"
  superuser:
    username: admin
    email: admin@example.com

namespace: statuspage